server {
    listen 8080;
    server_name localhost;
    root www;
    index index.html;
    dirindex off;
    error_page 404 /404.html;

    location / {
    }
    location /uploads {
        upload_dir www/uploads
        dirindex on;
    }
}
