server {
    listen 8080;
    server_name localhost;
    root www;
    index index.html;
    dirindex off;
    error_page 404 errors/404.html;

    location /uploads {
        upload_dir www/uploads
        dirindex on;
    }

    location /admin {
        redirect http://test.localhost
    }

    location /api {
        redirect http://test.localhost
    }
}

server {
    listen 9001
    server_name test.localhost
    root www/api

    # location /php {
    #     cgi .php 
    # }

    location /cgi-bin {
        root www
        cgi .py /usr/bin/python3
    }
}